"""Configuration for CDHT."""

CDHT_PEER_ID_RANGE = range(256)

CDHT_HOST = '127.0.0.1'
CDHT_UDP_BASE_PORT = 50000
CDHT_TCP_BASE_PORT = 50000
CDHT_TRANSFER_TIMEOUT_SEC = 1

CDHT_PING_INTERVAL_SEC = 20
CDHT_PING_TIMEOUT_SEC = 1
CDHT_PING_RETRIES = 3
